### PR TITLE
Converted all components to functional while maintaining code style

### PR DESCRIPTION
**Pull request by pandasa123**
I saw there's a branch already but that modified code style heavily. Here's a version that doesn't do that

### CODE REVIEW

**Comment by ajwann** [comment]
Hey thanks for the PR @pandasa123 ! Since the other PR was put up first, I'm going to give that one priority for the time being.

**Comment by pandasa123** [comment]
Sure sounds good! I'd say to define some code style then before adding linting / tests?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ajwann** [comment]
I'm not very picky on code style personally, I like to follow the coding standard set by big React shops like [AirBnB](https://www.npmjs.com/package/eslint-config-airbnb) and Facebook. If you want to just grab one of their eslint config packages (or a similar shop) that would be great.

**Comment by ajwann** [comment]
@pandasa123 Since the other PR was put up first I went ahead and took those changes. I'm going to go ahead an close this one, but I definitely appreciate your help!

**Pull request closed without merging**
