### PR TITLE
Added viewBoxes, #31

### PR DESCRIPTION
**Pull request by massrain**
Values for each taken from original [SVG Loaders](https://github.com/SamHerbert/SVG-Loaders) library.

### CODE REVIEW

**Comment by abuuzayr** [comment]
Nice work @massrain! I was going to work on #31 then realised that you already made the required changes. 

In any case, I wrote the tests for the 12 files that the viewBox prop should be present as @ajwann described. Do you want to add them in or should I set up another PR? I am OK either way.

Its a simple test to add to each test file, e.g. this for the Audio component in `audio.test.js`:

```
  it('viewBox property is defined', () => {
    const AudioComponent = mount(<Audio />).find('svg');
    expect(AudioComponent.prop('viewBox')).toBeDefined()
  });
```

**Comment by massrain** [comment]
> Nice work @massrain! I was going to work on #31 then realised that you already made the required changes.
> 
> In any case, I wrote the tests for the 12 files that the viewBox prop should be present as @ajwann described. Do you want to add them in or should I set up another PR? I am OK either way.
> 
> Its a simple test to add to each test file, e.g. this for the Audio component in `audio.test.js`:
> 
> ```
>   it('viewBox property is defined', () => {
>     const AudioComponent = mount(<Audio />).find('svg');
>     expect(AudioComponent.prop('viewBox')).toBeDefined()
>   });
> ```

Thank you very much, i have added according to your example. If not right, you can set up another PR.

**Comment by abuuzayr** [comment]
LGTM!

**Comment by ajwann** [comment]
Hey all of these changes look good! Thanks for your help @massrain and @abuuzayr!

**Pull request merged**
